{
	"version": 1699517362,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/boxs-sheet0.png",
		"images/bluebox-sheet0.png",
		"images/redbox-sheet0.png",
		"images/right_arrow-sheet0.png",
		"images/left_arrow-sheet0.png",
		"images/bluecheck-sheet0.png",
		"images/redcheck-sheet0.png",
		"images/box_line-sheet0.png",
		"images/splash_bg-sheet0.png",
		"images/bg-sheet0.png",
		"images/home_bt-sheet0.png",
		"images/play_pause_bt-sheet0.png",
		"images/play_pause_bt-sheet1.png",
		"images/play_bt-sheet0.png",
		"images/smile_mini_logo-sheet0.png",
		"images/bg_2-sheet0.png",
		"images/smile_mini_logo2-sheet0.png",
		"images/speaker_bt-sheet0.png",
		"images/speaker_bt-sheet1.png",
		"media/yop.m4a",
		"media/yop.ogg",
		"media/dog.m4a",
		"media/dog.ogg",
		"media/mattoglseby - 4.m4a",
		"media/mattoglseby - 4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}